#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define BASE 4          // Solo 4 caratteri: A, C, G, T
#define PRIME 101       // Numero primo per modulo hash

// Codifica A, C, G, T in 0-3
int codificaNucleotide(char c) {
    switch (c) {
        case 'A': return 0;
        case 'C': return 1;
        case 'G': return 2;
        case 'T': return 3;
        default: return -1; // Errore se DNA non valido
    }
}


char* readFile(const char* nomeFile) {
    FILE *file = fopen(nomeFile, "r");
    if (!file) {
        perror("Errore apertura file");
        exit(EXIT_FAILURE);
    }

    fseek(file, 0, SEEK_END);
    long lunghezza = ftell(file);
    rewind(file);

    char *buffer = malloc(lunghezza + 1);
    if (!buffer) {
        perror("Errore allocazione memoria");
        exit(EXIT_FAILURE);
    }

    fread(buffer, 1, lunghezza, file);
    buffer[lunghezza] = '\0';

    fclose(file);
    return buffer;
}

void cercaSequenzaDNA(char *genoma, char *sequenza) {
    int lenPattern = strlen(sequenza);
    int lenGenoma = strlen(genoma);
    int hashPattern = 0;
    int hashFinestra = 0;
    int fattore = 1;
    int i, j;

    // Calcola BASE^(lenPattern - 1) % PRIME
    for (i = 0; i < lenPattern - 1; i++)
        fattore = (fattore * BASE) % PRIME;

    // Calcola hash della sequenza target e della prima finestra del genoma
    for (i = 0; i < lenPattern; i++) {
        hashPattern = (BASE * hashPattern + codificaNucleotide(sequenza[i])) % PRIME;
        hashFinestra = (BASE * hashFinestra + codificaNucleotide(genoma[i])) % PRIME;
    }

    // Sliding window sul genoma
    for (i = 0; i <= lenGenoma - lenPattern; i++) {
        if (hashPattern == hashFinestra) {
            for (j = 0; j < lenPattern; j++) {
                if (genoma[i + j] != sequenza[j])
                    break;
            }
            
            if (j == lenPattern){
                printf("Sequenza trovata all’indice %d\n", i);
            }
        }

        if (i < lenGenoma - lenPattern) {
            hashFinestra = (BASE * (hashFinestra - codificaNucleotide(genoma[i]) * fattore)
                            + codificaNucleotide(genoma[i + lenPattern])) % PRIME;
            if (hashFinestra < 0)
                hashFinestra += PRIME;
        }
    }
}

int main(int argc, char const *argv[]) {
    int i=0;
    if (argc != 3)
	{
		printf("Errore, inserire nome file\n");
		exit(1);
	}

    char *pattern = readFile((char*)argv[2]);
	char *genoma = readFile((char*)argv[1]);


    // char genoma[] = "TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAAACCCTAAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCCTAACCCTAACCCTAACCCTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTCGCGGTACCCTCAGCCGGCCCGCCCGCCCGGGTCTGACCTGAGGAGAACTGTGCTCCGCCTTCAGAGTACCACCGAAATCTGTGCAGAGGACAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGTTGCAAAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGACACATGCTAGCGCGTCGGGGTGGAGGCGTGGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGACACATGCTACCGCGTCCAGGGGTGGAGGCGTGGCGCAGGCGCAGAGAGGCGCACCGCGCCGGCGCAGGCGCAGAGACACATGCTAGCGCGTCCAGGGGTGGAGGCGTGGCGCAGGCGCAGAGACGCAAGCCTACGGGCGGGGGTTGGGGGGGCGTGTGTTGCAGGAGCAAAGTCGCACGGCGCCGGGCTGGGGCGGGGGGAGGGTGGCGCCGTGCACGCGCAGAAACTCACGTCACGGTGGCGCGGCGCAGAGACGGGTAGAACCTCAGTAATCCGAAAAGCCGGGATCGACCGCCCCTTGCTTGCAGCCGGGCACTACAGGACCCGCTTGCTCACGGTGCTGTGCCAGGGCGCCCCCTGCTGGCGACTAGGGCAACTGCAGGGCTCTCTTGCTTAGAGTGGTGGCCAGCGCCCCCTGCTGGCGCCGGGGCACTGCAGGGCCCTCTTGCTTACTGTATAGTGGTGGCACGCCGCCTGCTGGCAGCTAGGGACATTGCAGGGTCCTCTTGCTCAAGGTGTAGTGGCAGCACGCCCACCTGCTGGCAGCTGGGGACACTGCCGGGCCCTCTTGCTCCAACAGTACTGGCGGATTATAGGGAAACACCCGGAGCATATGCTGTTTGGTCTCAGTAGACTCCTAAATATGGGATTCCTGGGTTTAAAAGTAAAAAATAAATATGTTTAATTTGTGAACTGATTACCATCAGAATTGTACTGTTCTGTATCCCACCAGCAATGTCTAGGAATGCCTGTTTCTCCACAAAGTGTTTACTTTTGGATTTTTGCCAGTCTAACAGGTGAAGCCCTGGAGATTCTTATTAGTGATTTGGGCTGGGGCCTGGCCATGTGTATTTTTTTAAATTTCCACTGATGATTTTGCTGCATGGCCGGTGTTGAGAATGACTGCGCAAATTTGCCGGATTTCCTTTGCTGTTCCTGCATGTAGTTTAAACGAGATTGCCAGCACCGGGTATCATTCACCATTTTTCTTTTCGTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGATGCTGTGGTCTTCATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGGGCCATTGTTCATCTTCTGGCCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGGAAAGATTGGAGGAAAGATGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAGTAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAGCCCAAAGCCGGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCTTTGGCCCTGGGAGAGCAGGTGGAAGATCAGGCAGGCCATCGCTGCCACAGAACCCAGTGGATTGGCCTAGGTGGGATCTCTGAGCTCAACAAG";
    // char sequenza[] = "TAACCCTA";

    cercaSequenzaDNA(genoma, pattern);

    // Libera memoria
    free(genoma);
    free(pattern);

    return 0;
}
